name: "Build"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      project-name:
        description: 'The name of the project'
        default: MailKitSimplified
        type: string
    outputs:
      artifact:
        description: 'Artifact name'
        value: ${{ jobs.build.outputs.artifact }}

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    env:
      SOURCE: "source"
      SENDER: "${{ inputs.project-name }}.Sender"
      RECEIVER: "${{ inputs.project-name }}.Receiver"

    outputs:
      artifact: ${{ env.SOURCE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # https://github.com/actions/setup-dotnet
    - name: Get .NET externals
      uses: actions/setup-dotnet@v3

    - name: Restore project dependencies
      run: |
        Get-ChildItem -Path "./${{ env.SOURCE }}" -Filter "*er.csproj" -File -Recurse |
        Select-Object -ExpandProperty BaseName | ForEach-Object {
          dotnet restore "./${{ env.SOURCE }}/$_/$_.csproj" #Write-Output
        }

    # https://github.com/actions/upload-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SOURCE }}
        path: |
          ${{ env.SOURCE }}/${{ env.SENDER }}
          ${{ env.SOURCE }}/${{ env.RECEIVER }}
        retention-days: 1
        if-no-files-found: error # or 'ignore', defaults to `warn`
