name: Development

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/**

# Cancel any other running workflows with the same ID
concurrency:
  group: ci-development-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    name: 🧱 CI/CD
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: development
      project-name: MailKitSimplified
    secrets: inherit
