name: RC
run-name: Publish as a Release Canidate

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

# Cancel any other running workflows with the same ID
concurrency:
  group: cd-rc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build-test.yml
    with:
      environment: release
      project-name: MailKitSimplified
      configuration: Release
    secrets: inherit

  deploy:
    needs: build
    name: 🚀 MailKitSimplified
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: release
    env:
      PACKAGE_NAME: 'MailKitSimplified.${{ needs.build.outputs.version }}.nupkg'

    steps:
      - name: Markdown workflow job summary
        run: echo "### $PACKAGE_NAME package ready to be published" >> $GITHUB_STEP_SUMMARY

      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: MailKitSimplified

      # - name: Publish to NuGet using the .NET environment
      #   uses: actions/setup-dotnet@v3
      #   run: dotnet nuget push $PACKAGE_NAME --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate