name: Release
run-name: Publish release branch or SemVer tags

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
    branches:
      - release/**

# Cancel any other running workflows with the same ID
concurrency:
  group: cd-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    name: 🧱 CI/CD
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: release
      project-name: MailKitSimplified
    secrets: inherit
